import React from "react";
import one from "../assets/icons/one.png";
import two from "../assets/icons/two.png";
import three from "../assets/icons/three.png";
import "./procedure.scss";
function Procedure() {
  return (
    <>
      <div className="procedure">
        <div className="procedure__heading">
          How <span style={{ color: "black" }}>Dermacare </span>works ?
          <hr />
        </div>

        <div className="procedureContainer">
          <div className="procedureContainer__div1">
            <div className="procedureContainer__div1__Image">
              {/* <img src={one} alt="" className="one-section" /> */}
            </div>
            {/* <div className="procedureContainer__div1__Heading"> */}
            {/* </div> */}
            <div className="procedureContainer__div1__Content">
              <p className="content-head">Click & Upload</p>
              <p>
                Navigate to the upload section through the button placed at the
                bottom of the login form. Upload atleast 3 images of the
                affected part of skin of your body. Make sure the images are
                taken from different angles.
              </p>
            </div>
          </div>

          <div className="procedureContainer__div2">
            <div className="procedureContainer__div2__TwoImage">
              {/* <img src={two} alt="" className="two-section" /> */}
              {/* <div className="procedureContainer__div2__TwoHeading">
              </div> */}
              <div className="procedureContainer__div2__TwoContent">
                <p className="content-head">View your Diagnosis Report</p>
                <p>
                  Upon successful upload of images,head over to the profile
                  section through the person icon placed at top right corner of
                  navigation panel where you can access the report generated by
                  our model.
                </p>
              </div>
            </div>
          </div>

          <div className="procedureContainer__div3">
            <div className="procedureContainer__div3__ThreeImage">
              {/* <img src={three} alt="" className="three-section" /> */}
              {/* <div className="procedureContainer__div3__ThreeHeading">
              </div> */}
              <div className="procedureContainer__div3__ThreeContent">
                <p className="content-head">Access via Email</p>
                <p>
                  A copy of the diagnosis report will be mailed to the user as
                  well keeping in mind their convenience and easy storage.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Procedure;
